
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[188] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   74,   72,   71,   70,
       71,   45,   55,   38,   43,   22,   46,   47,   37,   52,
       37,   72,   38,   17,   53,   42,   41,   42,   54,   48,
       49,   43,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   50,   43,   51,   65,   64,   65,   65,   69,
       68,   69,   69,   25,   23,   25,   24,   26,   73,   31,
       33,   28,   27,   28,   30,   29,   35,   34,   35,   36,
       60,   61,   60,   59,   60,   71,   70,   42,   44,   39,
       40,   19,   66,   62,   18,   21,   17,    0,   43,   54,

       54,   54,   54,   54,   54,    5,   54,   54,   54,    1,
       54,   54,   54,   54,   54,   64,   63,    0,   68,   67,
       23,   32,   27,   34,   61,   57,    0,   58,   56,   20,
        0,    0,   19,   54,   54,   54,   54,   54,   54,   54,
       54,    3,    7,   54,   54,   54,   54,   20,    0,    0,
       19,   21,   54,   14,    8,   54,   54,   54,    2,   54,
       54,   54,   11,   54,    0,   20,   21,    0,    6,   54,
       54,   54,    9,   54,   54,    4,    0,   21,   54,   54,
       10,   12,   13,   54,   15,   16,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    8,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       28,   29,   30,   31,   26,    1,   32,   33,   34,   35,

       36,   37,   26,   38,   39,   26,   40,   41,   26,   42,
       43,   26,   26,   44,   45,   46,   47,   48,   49,   26,
       26,   26,   50,   51,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    1,    2,    2,    2,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    2,    3,
        3,    2,    2,    2,    1,    3,    3,    2,    1,    2,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    2,
        2,    2
    } ;

static const flex_int16_t yy_base[197] =
    {   0,
        0,    0,   50,   52,   54,   56,   58,   60,   79,  117,
       62,   71,   74,   91,   93,  100,  316,  317,  113,  317,
      128,  291,  317,  317,  304,  317,  317,  317,  298,  317,
      295,   71,   53,  120,  317,   82,  287,   85,    0,  317,
      317,  317,  266,   81,   40,  268,   45,   97,  272,  258,
      263,  267,  317,  253,  317,  317,  317,  300,  132,  317,
      317,  299,  282,  317,  317,  297,  317,  317,  317,  288,
      317,  317,  317,  295,  317,  317,  317,  317,  294,  317,
      317,  317,  293,  317,  163,  140,  317,  317,  317,  317,
      317,  137,  317,  317,  151,  131,  161,  169,  317,    0,

      259,  249,  261,  250,  254,  243,  244,  245,  243,    0,
      240,  239,  245,  244,  243,  317,  317,  278,  317,  317,
      317,  317,  317,  317,  317,  317,  277,  317,  317,  181,
      193,  155,  173,  247,  242,  233,  229,  219,  217,  213,
      213,    0,    0,  193,  189,  194,  185,  195,  203,  164,
      207,  212,  181,    0,    0,  173,  159,  139,    0,  131,
      124,  128,    0,  124,  178,  183,  216,  221,    0,  111,
      107,  107,    0,   84,   82,    0,  198,  226,   67,   55,
        0,    0,    0,   62,    0,    0,  317,  252,  255,  258,
      261,  264,  267,  270,  273,   77

    } ;

static const flex_int16_t yy_def[197] =
    {   0,
      187,    1,  188,  188,  189,  189,  190,  190,  191,  191,
      192,  192,  193,  193,  194,  194,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  195,  187,  187,  187,  187,  196,  187,
      187,  187,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  195,  187,  195,  187,  187,  196,

      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  187,  187,  187,
      187,  187,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  187,  187,  187,  187,  196,  196,
      196,  196,  196,  196,  196,  196,  187,  187,  196,  196,
      196,  196,  196,  196,  196,  196,    0,  187,  187,  187,
      187,  187,  187,  187,  187,  187

    } ;

static const flex_int16_t yy_nxt[370] =
    {   0,
       18,   19,   20,   21,   19,   22,   23,   18,   24,   25,
       26,   27,   28,   24,   29,   30,   31,   32,   33,   34,
       34,   35,   36,   37,   38,   39,   39,   40,   18,   41,
       42,   39,   43,   44,   45,   46,   47,   39,   48,   39,
       39,   39,   39,   49,   50,   39,   39,   51,   52,   53,
       54,   55,   57,   58,   57,   58,   61,   62,   61,   62,
       65,   66,   65,   66,   73,   74,   93,   63,   67,   63,
       67,   94,   75,   73,   74,  105,   78,   79,   59,  100,
       59,   75,  106,   76,   80,  108,   68,  109,   68,   70,
       92,   92,   76,   78,   79,   82,   83,  186,   71,   84,

      185,   80,   82,   83,   99,   88,   84,   71,   88,   99,
       71,   71,  102,  184,   86,   71,   86,   86,  103,  183,
       71,   85,   71,  104,   71,  182,   71,   70,   85,   86,
       87,   86,   86,  110,  117,  118,   71,   96,  111,   97,
       97,   86,  181,   86,   86,   71,   98,  180,   71,   71,
       92,   92,  179,   71,  130,   98,   92,   92,   71,  176,
       71,  175,   71,  131,   71,  126,  127,  174,  187,  128,
      187,  187,  131,  129,  133,  133,  173,  187,   96,  172,
       97,   97,  129,  151,  151,  132,  187,   98,  133,  133,
      152,  129,  133,  133,  129,  129,   98,  166,  166,  129,

      148,  148,  166,  166,  129,  171,  129,  149,  129,  150,
      129,  170,  151,  151,  148,  148,  149,  178,  178,  165,
      169,  149,  166,  166,  130,  164,  151,  151,  163,  152,
      149,  167,  167,  152,  162,  167,  167,  177,  168,  161,
      178,  178,  168,  152,  160,  178,  178,  168,  159,  158,
      157,  168,   56,   56,   56,   60,   60,   60,   64,   64,
       64,   69,   69,   69,   72,   72,   72,   77,   77,   77,
       81,   81,   81,   95,  156,   95,  155,  154,  153,  126,
      117,  147,  146,  145,  144,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  134,  125,  124,  123,  122,  121,

      120,  119,  116,   89,  115,  114,  113,  112,  107,  101,
       88,   91,   90,   89,   88,  187,   17,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187
    } ;

static const flex_int16_t yy_chk[370] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    4,    4,    5,    5,    6,    6,
        7,    7,    8,    8,   11,   11,   33,    5,    7,    6,
        8,   33,   11,   12,   12,   45,   13,   13,    3,  196,
        4,   12,   45,   11,   13,   47,    7,   47,    8,    9,
       32,   32,   12,   14,   14,   15,   15,  184,    9,   15,

      180,   14,   16,   16,   36,   36,   16,    9,   38,   38,
        9,    9,   44,  179,   19,    9,   19,   19,   44,  175,
        9,   15,    9,   44,    9,  174,    9,   10,   16,   21,
       21,   21,   21,   48,   59,   59,   10,   34,   48,   34,
       34,   86,  172,   86,   86,   10,   34,  171,   10,   10,
       96,   96,  170,   10,   92,   34,   92,   92,   10,  164,
       10,  162,   10,   92,   10,   85,   85,  161,   95,   85,
       95,   95,   92,   85,  132,  132,  160,   95,   97,  158,
       97,   97,   85,  150,  150,   98,   95,   97,   98,   98,
      133,   85,  133,  133,   85,   85,   97,  165,  165,   85,

      130,  130,  166,  166,   85,  157,   85,  130,   85,  131,
       85,  156,  131,  131,  148,  148,  130,  177,  177,  149,
      153,  148,  149,  149,  151,  147,  151,  151,  146,  152,
      148,  152,  152,  167,  145,  167,  167,  168,  152,  144,
      168,  168,  167,  178,  141,  178,  178,  152,  140,  139,
      138,  167,  188,  188,  188,  189,  189,  189,  190,  190,
      190,  191,  191,  191,  192,  192,  192,  193,  193,  193,
      194,  194,  194,  195,  137,  195,  136,  135,  134,  127,
      118,  115,  114,  113,  112,  111,  109,  108,  107,  106,
      105,  104,  103,  102,  101,   83,   79,   74,   70,   66,

       63,   62,   58,   54,   52,   51,   50,   49,   46,   43,
       37,   31,   29,   25,   22,   17,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1905065.l"







#line 11 "1905065.l"
#include<bits/stdc++.h>
#include "1905065_SymbolInfo.h"
#include "y.tab.h"

using namespace std;

extern int line_cnt, err_cnt, multi_line;
string cmnt, cstr, strASCI;
bool multi_string;
extern ofstream logout, errorout;
extern string idName,idType;

// void yylval.si = new SymbolInfo( yytext,string cstr, string strASCI=""){
// 	tokenout<<'<'<<cstr;
// 	if(strASCI!=""){
// 		tokenout<<", "<<strASCI;
// 	}
// 	tokenout<<">\n";

// }
void logPrint( string cstr, string strASCI){

	logout << "Line# " << line_cnt-multi_line << ": Token <"<<cstr<<"> Lexeme " << strASCI << " found\n";

}
extern void errorPrint(string cstr, string strASCI="");
string getSpecialChar(string s){
	int l= s.length();
	if(s[1]=='\\'){
    if(s[l-2] == 'n') return "\n";
    else if(s[l-2] == 't') return "\t";
    else if(s[l-2] == 'r') return "\r";
    else if(s[l-2] == 'a') return "\a";
    else if(s[l-2] == 'b') return "\b";
    else if(s[l-2] == 'f') return "\f";
    else if(s[l-2] == 'v') return "\v";
    else if(s[l-2] == '\\') return "\\";
    else if(s[l-2] == '\'') return "\'";
    else if(s[l-2] == '0') return "\0";
}
	string t(s,1,l-2);
    return t;

}
#line 640 "lex.yy.c"
#line 641 "lex.yy.c"

#define INITIAL 0
#define SINGLE_LINE_COMMENT 1
#define MULTILINE_COMMENT 2
#define SINGLE_QUOT_STARTS 3
#define SPECIAL_CHAR 4
#define NORMAL_CHAR 5
#define MULTI_CHAR_ERROR 6
#define STRING_STATE 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 65 "1905065.l"


#line 868 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 188 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 317 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 67 "1905065.l"
{
	yylval.si = new SymbolInfo( yytext,"IF", line_cnt-multi_line, line_cnt-multi_line,1);
	logPrint( "IF",yytext);	
	return IF;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 73 "1905065.l"
{
	yylval.si = new SymbolInfo( yytext,"ELSE", line_cnt-multi_line, line_cnt-multi_line,1);
	logPrint( "ELSE",yytext);	
	return ELSE ;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 78 "1905065.l"
{	
	logPrint( "FOR",yytext);
	yylval.si = new SymbolInfo( yytext,"FOR", line_cnt-multi_line, line_cnt-multi_line,1);
	return  FOR  ;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 83 "1905065.l"
{
	yylval.si = new SymbolInfo( yytext,"WHILE", line_cnt-multi_line, line_cnt-multi_line,1);
	logPrint( "WHILE",yytext);
	return  WHILE  ;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 88 "1905065.l"
{
	yylval.si = new SymbolInfo( yytext,"DO", line_cnt-multi_line, line_cnt-multi_line,1);
	logPrint( "DO",yytext);
	return  DO  ;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 94 "1905065.l"
{
	yylval.si = new SymbolInfo( yytext,"BREAK", line_cnt-multi_line, line_cnt-multi_line,1);
	logPrint( "BREAK",yytext);
	return  BREAK  ;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 99 "1905065.l"
{
	logPrint( "INT",yytext);
	yylval.si = new SymbolInfo( yytext,"INT", line_cnt-multi_line, line_cnt-multi_line,1);
	idType=yylval.si->type;
	return  INT  ;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "1905065.l"
{
	logPrint( "CHAR",yytext);
	yylval.si = new SymbolInfo( yytext,"CHAR", line_cnt-multi_line, line_cnt-multi_line,1);
	idType=(yylval.si)->type;
	return  CHAR  ;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 111 "1905065.l"
{
	logPrint( "FLOAT",yytext);
	
	yylval.si = new SymbolInfo( yytext,"FLOAT", line_cnt-multi_line, line_cnt-multi_line,1);
	idType=yylval.si->type;
	return  FLOAT  ;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 118 "1905065.l"
{
	logPrint( "DOUBLE",yytext);
	yylval.si = new SymbolInfo( yytext,"DOUBLE", line_cnt-multi_line, line_cnt-multi_line,1);
	idType=yylval.si->type;
	return  DOUBLE  ;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 124 "1905065.l"
{
	logPrint( "VOID",yytext);
	yylval.si = new SymbolInfo( yytext,"VOID", line_cnt-multi_line, line_cnt-multi_line,1);
	idType=yylval.si->type;
	return  VOID  ;
}	
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 130 "1905065.l"
{
	logPrint( "RETURN",yytext);
	yylval.si = new SymbolInfo( yytext,"RETURN", line_cnt-multi_line, line_cnt-multi_line,1);
	return  RETURN  ;
}	
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 135 "1905065.l"
{
	logPrint( "SWITCH",yytext);
	yylval.si = new SymbolInfo( yytext,"SWITCH", line_cnt-multi_line, line_cnt-multi_line,1);
	return  SWITCH  ;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 140 "1905065.l"
{
	logPrint( "CASE",yytext);
	yylval.si = new SymbolInfo( yytext,"CASE", line_cnt-multi_line, line_cnt-multi_line,1);
	return  CASE  ;
}		
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 145 "1905065.l"
{
	logPrint( "DEFAULT",yytext);
	yylval.si = new SymbolInfo( yytext,"DEFAULT", line_cnt-multi_line, line_cnt-multi_line,1);
	return  DEFAULT  ;
}		
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 150 "1905065.l"
{
	logPrint( "CONTINUE",yytext);
	yylval.si = new SymbolInfo( yytext,"CONTINUE", line_cnt-multi_line, line_cnt-multi_line,1);
	return  CONTINUE  ;
}	
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 158 "1905065.l"
{
	yylval.si = new SymbolInfo( yytext,"CONST_INT", line_cnt-multi_line, line_cnt-multi_line,1);
	yylval.si->dataType="INT";
	logPrint( "CONST_INT",yytext);
	return  CONST_INT  ;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 165 "1905065.l"
{
	err_cnt++;
	errorPrint("INVALID_ID_SUFFIX_NUM_PREFIX ",yytext);
}	
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 170 "1905065.l"
{
	yylval.si = new SymbolInfo( yytext,"CONST_FLOAT", line_cnt-multi_line, line_cnt-multi_line,1);
	yylval.si->dataType="FLOAT";
	logPrint( "CONST_FLOAT",yytext);				
	return  CONST_FLOAT  ;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 177 "1905065.l"
{
	err_cnt++;
	errorPrint("TOO_MANY_DECIMAL_POINTS ",yytext);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 182 "1905065.l"
{
	err_cnt++;
	errorPrint("ILLFORMED_NUMBER ",yytext);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 187 "1905065.l"
{
   cstr="'";
   BEGIN SINGLE_QUOT_STARTS;
}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 193 "1905065.l"
{
	err_cnt++;
   errorPrint("UNFINISHED_CONST_CHAR ",cstr);
   line_cnt++;
   cstr= "";
   BEGIN INITIAL;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 200 "1905065.l"
{
	cstr+=yytext;
	   err_cnt++;
   errorPrint("EMPTY_CONST_CHAR ",cstr);
   BEGIN INITIAL;
}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 206 "1905065.l"
{
   cstr +=yytext;
   BEGIN NORMAL_CHAR;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 211 "1905065.l"
{
		cstr+=yytext;
		BEGIN SPECIAL_CHAR;
}
	YY_BREAK
case YY_STATE_EOF(SINGLE_QUOT_STARTS):
#line 217 "1905065.l"
{
   err_cnt++;
	errorPrint("UNFINISHED_CONST_CHAR ",cstr);
   cstr="";
   BEGIN INITIAL;
}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 223 "1905065.l"
{
   errorPrint("UNFINISHED_CONST_CHAR ",cstr);
   err_cnt++;
   line_cnt++;
   BEGIN INITIAL;
}
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 229 "1905065.l"
{
   cstr +=yytext;
   BEGIN MULTI_CHAR_ERROR;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 233 "1905065.l"
{
	err_cnt++;
   errorPrint("UNFINISHED_CONST_CHAR ",cstr);
		logPrint( "SEMICOLON",yytext);
		yylval.si = new SymbolInfo( yytext,"SEMICOLON", line_cnt-multi_line, line_cnt-multi_line,1);   
   cstr="";
   BEGIN INITIAL;
   return  SEMICOLON  ;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 242 "1905065.l"
{

   cstr+=yytext;
   logPrint( "CONST_CHAR",getSpecialChar(cstr));
   yylval.si = new SymbolInfo(getSpecialChar(cstr),"CONST_CHAR", line_cnt-multi_line, line_cnt-multi_line,1);
   yylval.si->dataType="CHAR";
   cstr=""; 
   BEGIN INITIAL;
   return  CONST_CHAR ;
}
	YY_BREAK
case YY_STATE_EOF(NORMAL_CHAR):
#line 252 "1905065.l"
{
	err_cnt++;
	errorPrint("UNFINISHED_CONST_CHAR ",cstr);
   BEGIN INITIAL;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 257 "1905065.l"
{
	err_cnt++;
	cstr+=yytext;
   errorPrint("UNFINISHED_CONST_CHAR ",cstr);
   BEGIN INITIAL;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 263 "1905065.l"
{
	cstr+=yytext;
   logPrint( "CONST_CHAR","'");
   yylval.si = new SymbolInfo( "'","CONST_CHAR", line_cnt-multi_line, line_cnt-multi_line,1);
      yylval.si->dataType="CHAR";
   cstr=""; 
   BEGIN INITIAL;
   return  CONST_CHAR ;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 272 "1905065.l"
{
   cstr+=yytext;
   BEGIN NORMAL_CHAR;
}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 277 "1905065.l"
{
   err_cnt++;
   errorPrint("UNFINISHED_CONST_CHAR ",cstr);
   line_cnt++;
   cstr="";
   BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(MULTI_CHAR_ERROR):
#line 284 "1905065.l"
{
   err_cnt++;
      errorPrint("UNFINISHED_CONST_CHAR ",cstr);
   cstr="";
   BEGIN INITIAL;
}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 290 "1905065.l"
{
	cstr +=yytext;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 293 "1905065.l"
{
	cstr+=yytext;
   err_cnt++;
      errorPrint("MULTICHAR_CONST_CHAR ",cstr);
   cstr="";
   BEGIN INITIAL;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 301 "1905065.l"
{
	logPrint( "ADDOP",yytext);
	yylval.si = new SymbolInfo( yytext,"ADDOP", line_cnt-multi_line, line_cnt-multi_line,1);
	return  ADDOP  ;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 307 "1905065.l"
{
	logPrint( "MULOP",yytext);
	yylval.si = new SymbolInfo( yytext,"MULOP", line_cnt-multi_line, line_cnt-multi_line,1);
	return  MULOP  ;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 313 "1905065.l"
{
	logPrint( "INCOP",yytext);
	yylval.si = new SymbolInfo( yytext,"INCOP", line_cnt-multi_line, line_cnt-multi_line,1);
	return  INCOP  ;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 318 "1905065.l"
{
	logPrint( "DECOP",yytext);
	yylval.si = new SymbolInfo( yytext,"DECOP", line_cnt-multi_line, line_cnt-multi_line,1);
	return  DECOP  ;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 324 "1905065.l"
{
	logPrint( "ASSIGNOP",yytext);
	yylval.si = new SymbolInfo( yytext,"ASSIGNOP", line_cnt-multi_line, line_cnt-multi_line,1);
	return  ASSIGNOP  ;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 330 "1905065.l"
{
	logPrint( "RELOP",yytext);
	yylval.si = new SymbolInfo( yytext,"RELOP", line_cnt-multi_line, line_cnt-multi_line,1);
	return  RELOP  ;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 336 "1905065.l"
{
	logPrint( "BITOP",yytext);
	yylval.si = new SymbolInfo( yytext,"BITOP", line_cnt-multi_line, line_cnt-multi_line,1);
	return  BITOP  ;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 342 "1905065.l"
{
	logPrint( "LOGICOP",yytext);
	yylval.si = new SymbolInfo( yytext,"LOGICOP", line_cnt-multi_line, line_cnt-multi_line,1);
	return  LOGICOP  ;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 348 "1905065.l"
{
	logPrint( "NOT",yytext);
	yylval.si = new SymbolInfo( yytext,"NOT", line_cnt-multi_line, line_cnt-multi_line,1);
	return  NOT  ;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 354 "1905065.l"
{
	logPrint( "LPAREN",yytext);
	yylval.si = new SymbolInfo( yytext,"LPAREN", line_cnt-multi_line, line_cnt-multi_line,1);
	return  LPAREN  ;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 359 "1905065.l"
{
	logPrint( "RPAREN",yytext);
	yylval.si = new SymbolInfo( yytext,"RPAREN", line_cnt-multi_line, line_cnt-multi_line,1);
	return  RPAREN  ;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 364 "1905065.l"
{
	logPrint( "LSQUARE",yytext);
	yylval.si = new SymbolInfo( yytext,"LSQUARE", line_cnt-multi_line, line_cnt-multi_line,1);
	return  LSQUARE  ;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 369 "1905065.l"
{
	logPrint( "RSQUARE",yytext);
	yylval.si = new SymbolInfo( yytext,"RSQUARE", line_cnt-multi_line, line_cnt-multi_line,1);
	return  RSQUARE  ;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 374 "1905065.l"
{
	logPrint( "LCURL",yytext);
	yylval.si = new SymbolInfo( yytext,"LCURL", line_cnt-multi_line, line_cnt-multi_line,1);
	//st.enterScope();
	return  LCURL  ;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 380 "1905065.l"
{
	logPrint( "RCURL",yytext);
	yylval.si = new SymbolInfo( yytext,"RCURL", line_cnt-multi_line, line_cnt-multi_line,1);
	//st.exitScope();
	return  RCURL  ;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 387 "1905065.l"
{
	logPrint( "COMMA",yytext);
	yylval.si = new SymbolInfo( yytext,"COMMA", line_cnt-multi_line, line_cnt-multi_line,1);
	return  COMMA  ;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 392 "1905065.l"
{
	logPrint( "SEMICOLON",yytext);
	yylval.si = new SymbolInfo( yytext,"SEMICOLON", line_cnt-multi_line, line_cnt-multi_line,1);
	return  SEMICOLON  ;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 398 "1905065.l"
{
		logPrint( "ID",yytext);
		idName=yytext;
		yylval.si = new SymbolInfo( yytext,"ID", line_cnt-multi_line, line_cnt-multi_line,1);
		// bool success = st.insert(yytext,"ID");
		// if(success){
		// 	st.printAllScopeTables(logout);;
		// }
		// else {
		// 	logout<<"\t"<<yytext<<" already exisits in the current ScopeTable" << endl;
		// }
		
		return  ID  ;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 412 "1905065.l"
{
		multi_string=false;
		cstr=yytext;
		strASCI="";
		multi_line=0;
		BEGIN STRING_STATE;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 420 "1905065.l"
{
	cstr+=yytext;
	string p="'";
	p+=yytext;
	p+="'";
	strASCI+=getSpecialChar(p);
}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 429 "1905065.l"
{
	multi_string=true;
	multi_line++;
	line_cnt++;
	cstr+=yytext;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 436 "1905065.l"
{
	cstr+=yytext;
	strASCI+='\"';
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 441 "1905065.l"
{
	cstr+=yytext;
	 
	if(!multi_string){
		yylval.si = new SymbolInfo( strASCI,"SINGLE_LINE_STRING", line_cnt-multi_line, line_cnt-multi_line,1);
		logPrint( "SINGLE LINE STRING",cstr);
		return SINGLE_LINE_STRING;
	}
	else{
		yylval.si = new SymbolInfo( strASCI,"MULTI LINE STRING", line_cnt-multi_line, line_cnt-multi_line,1);
		logPrint( "MULTI LINE STRING",cstr);
		return  MULTILINE_STRING ;
	}
	 
	multi_line=0;
	cstr="";
	strASCI="";	
	multi_string=false;
	BEGIN INITIAL;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 462 "1905065.l"
{
	cstr+=yytext;
	strASCI+=yytext;
}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 467 "1905065.l"
{

	multi_line=0; 
	errorPrint("UNFINISHED_STRING ",cstr);
	 
	err_cnt++;
	line_cnt++;
	
	cstr="";
	strASCI="";	
	multi_string=false;
	BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(STRING_STATE):
#line 481 "1905065.l"
{
	errorPrint("UNFINISHED_STRING ",cstr);
	err_cnt++;
	
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 487 "1905065.l"
{
	cmnt="//";
	multi_line=0;
	BEGIN SINGLE_LINE_COMMENT;

}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 493 "1905065.l"
{
		cmnt+=yytext;
		multi_line++;
		line_cnt++;
}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 498 "1905065.l"
{
		 
		logPrint( "SINGLE LINE COMMENT", cmnt);
		 
		multi_line=0;
		line_cnt++;
		cmnt="";
		BEGIN INITIAL;
   
}
	YY_BREAK
case YY_STATE_EOF(SINGLE_LINE_COMMENT):
#line 508 "1905065.l"
{
	logPrint( "SINGLE LINE COMMENT", cmnt);
	cmnt="";
	multi_line=0;
	
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 514 "1905065.l"
{
	cmnt+=yytext;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 518 "1905065.l"
{
	cmnt="/*";
	multi_line=0;
	BEGIN MULTILINE_COMMENT;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 523 "1905065.l"
{
	cmnt+="*/";
	 
	logPrint( "MULTI LINE COMMENT",cmnt);
	 
	multi_line=0;
	cmnt="";
	BEGIN INITIAL;
}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 534 "1905065.l"
{
	cmnt+=yytext;
	multi_line++;
   line_cnt++;
   
}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 541 "1905065.l"
{
   multi_line=0;
   errorPrint("UNFINISHED_COMMENT ",cmnt);
   err_cnt++;
   cmnt="";
   
   BEGIN INITIAL;
	
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 551 "1905065.l"
{
   cmnt+=yytext;
}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 555 "1905065.l"
{
	line_cnt++;
	
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 560 "1905065.l"
{}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 562 "1905065.l"
{
   err_cnt++;
	logout<<"Error at line# "+to_string(line_cnt-multi_line)+": UNRECOGNIZED CHAR "+yytext<<endl;
	
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 568 "1905065.l"
ECHO;
	YY_BREAK
#line 1704 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SPECIAL_CHAR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 188 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 188 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 187);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 568 "1905065.l"


// int main(int argc, char** argv) {
// 	if(argc!=2){
// 		cout<<"Please provide input file name and try again\n";
// 		return 0;
// 	}
	
// 	FILE *fin=fopen(argv[1],"r");
// 	if(fin==NULL){
// 		cout<<"Cannot open specified file\n";
// 		return 0;
// 	}
	
// 	logout.open("1905065_log.txt");
// 	tokenout.open("1905065_token.txt");

// 	yyin= fin;
// 	yylex();
// 	st.printAllScopeTables(logout);
//  	logout << "Total lines: " << line_cnt << endl;
//  	logout << "Total errors: " << err_cnt << endl;
// 	fclose(yyin);
// 	tokenout.close();
// 	logout.close();
// 	return 0;
// }

